// 후대의 개발자님께 : 컴포넌트 맨 첫글자가 대문자로 시작하지 않으면 JSX 컴포넌트가 아니라 일반 HTML 태그로 인식합니다. 제발 대문자로 시작해주세요.
import {
  Accordion,
  AccordionActions,
  AccordionDetails,
  AccordionSummary,
  Alert,
  AlertTitle,
  AppBar,
  Autocomplete,
  Avatar,
  AvatarGroup,
  Backdrop,
  Badge,
  BottomNavigation,
  BottomNavigationAction,
  Box,
  Breadcrumbs,
  Button,
  ButtonBase,
  ButtonGroup,
  Card,
  CardActionArea,
  CardActions,
  CardContent,
  CardHeader,
  CardMedia,
  Checkbox,
  Chip,
  CircularProgress,
  Collapse,
  Container,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  Drawer,
  Fab,
  Fade,
  FilledInput,
  FormControl,
  FormControlLabel,
  FormGroup,
  FormHelperText,
  FormLabel,
  Grid,
  Grow,
  Icon,
  IconButton,
  ImageList,
  ImageListItem,
  ImageListItemBar,
  Input,
  InputAdornment,
  InputBase,
  InputLabel,
  LinearProgress,
  Link,
  List,
  ListItem,
  ListItemAvatar,
  ListItemButton,
  ListItemIcon,
  ListItemSecondaryAction,
  ListItemText,
  ListSubheader,
  Menu,
  MenuItem,
  MenuList,
  MobileStepper,
  Modal,
  NativeSelect,
  NoSsr,
  OutlinedInput,
  Pagination,
  PaginationItem,
  Paper,
  Popover,
  Popper,
  Portal,
  Radio,
  RadioGroup,
  Rating,
  Select,
  Skeleton,
  Slide,
  Slider,
  Snackbar,
  SnackbarContent,
  SpeedDial,
  SpeedDialAction,
  SpeedDialIcon,
  Stack,
  Step,
  StepButton,
  StepConnector,
  StepContent,
  StepIcon,
  StepLabel,
  Stepper,
  SvgIcon,
  SwipeableDrawer,
  Switch,
  Tab,
  TabScrollButton,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableFooter,
  TableHead,
  TablePagination,
  TableRow,
  TableSortLabel,
  Tabs,
  TextField,
  TextareaAutosize,
  ToggleButton,
  ToggleButtonGroup,
  Toolbar,
  Tooltip,
  Typography,
  Zoom,
} from "@mui/material";
import type { MDXComponents } from "mdx/types.js";
import { createElement } from "react";

import { LottiePlayer, NetworkLottiePlayer } from "@frontend/common/components";
import {
  Confetti,
  FAQAccordion,
  Map as MDXMap,
  PrimaryStyledDetails,
  SecondaryStyledDetails,
  SessionList,
  SessionTimeTable,
  StyledFullWidthButton,
} from "@frontend/common/components/mdx_components";
import { PriceDisplay, ShopContextProvider, SignInGuard, UserSignInAccount, UserSignInMethod } from "@frontend/shop/components/common";
import { CartStatus, OrderList, PatronList, ProductImageCardList, ProductList, UserInfo } from "@frontend/shop/components/features";

const MUIMDXComponents: MDXComponents = {
  Mui__material__Accordion: Accordion,
  Mui__material__AccordionActions: AccordionActions,
  Mui__material__AccordionDetails: AccordionDetails,
  Mui__material__AccordionSummary: AccordionSummary,
  Mui__material__Alert: Alert,
  Mui__material__AlertTitle: AlertTitle,
  Mui__material__AppBar: AppBar,
  Mui__material__Autocomplete: Autocomplete,
  Mui__material__Avatar: Avatar,
  Mui__material__AvatarGroup: AvatarGroup,
  Mui__material__Backdrop: Backdrop,
  Mui__material__Badge: Badge,
  Mui__material__BottomNavigation: BottomNavigation,
  Mui__material__BottomNavigationAction: BottomNavigationAction,
  Mui__material__Box: Box,
  Mui__material__Breadcrumbs: Breadcrumbs,
  Mui__material__Button: Button,
  Mui__material__ButtonBase: ButtonBase,
  Mui__material__ButtonGroup: ButtonGroup,
  Mui__material__Card: Card,
  Mui__material__CardActionArea: CardActionArea,
  Mui__material__CardActions: CardActions,
  Mui__material__CardContent: CardContent,
  Mui__material__CardHeader: CardHeader,
  Mui__material__CardMedia: CardMedia,
  Mui__material__Checkbox: Checkbox,
  Mui__material__Chip: Chip,
  Mui__material__CircularProgress: CircularProgress,
  Mui__material__Collapse: Collapse,
  Mui__material__Container: Container,
  Mui__material__Dialog: Dialog,
  Mui__material__DialogActions: DialogActions,
  Mui__material__DialogContent: DialogContent,
  Mui__material__DialogContentText: DialogContentText,
  Mui__material__DialogTitle: DialogTitle,
  Mui__material__Divider: Divider,
  Mui__material__Drawer: Drawer,
  Mui__material__Fab: Fab,
  Mui__material__Fade: Fade,
  Mui__material__FilledInput: FilledInput,
  Mui__material__FormControl: FormControl,
  Mui__material__FormControlLabel: FormControlLabel,
  Mui__material__FormGroup: FormGroup,
  Mui__material__FormHelperText: FormHelperText,
  Mui__material__FormLabel: FormLabel,
  Mui__material__Grid: Grid,
  Mui__material__Grow: Grow,
  Mui__material__Icon: Icon,
  Mui__material__IconButton: IconButton,
  Mui__material__ImageList: ImageList,
  Mui__material__ImageListItem: ImageListItem,
  Mui__material__ImageListItemBar: ImageListItemBar,
  Mui__material__Input: Input,
  Mui__material__InputAdornment: InputAdornment,
  Mui__material__InputBase: InputBase,
  Mui__material__InputLabel: InputLabel,
  Mui__material__LinearProgress: LinearProgress,
  Mui__material__Link: Link,
  Mui__material__List: List,
  Mui__material__ListItem: ListItem,
  Mui__material__ListItemAvatar: ListItemAvatar,
  Mui__material__ListItemButton: ListItemButton,
  Mui__material__ListItemIcon: ListItemIcon,
  Mui__material__ListItemSecondaryAction: ListItemSecondaryAction,
  Mui__material__ListItemText: ListItemText,
  Mui__material__ListSubheader: ListSubheader,
  Mui__material__Menu: Menu,
  Mui__material__MenuItem: MenuItem,
  Mui__material__MenuList: MenuList,
  Mui__material__MobileStepper: MobileStepper,
  Mui__material__Modal: Modal,
  Mui__material__NativeSelect: NativeSelect,
  Mui__material__NoSsr: NoSsr,
  Mui__material__OutlinedInput: OutlinedInput,
  Mui__material__Pagination: Pagination,
  Mui__material__PaginationItem: PaginationItem,
  Mui__material__Paper: Paper,
  Mui__material__Popover: Popover,
  Mui__material__Popper: Popper,
  Mui__material__Portal: Portal,
  Mui__material__Radio: Radio,
  Mui__material__RadioGroup: RadioGroup,
  Mui__material__Rating: Rating,
  Mui__material__Select: Select,
  Mui__material__Skeleton: Skeleton,
  Mui__material__Slide: Slide,
  Mui__material__Slider: Slider,
  Mui__material__Snackbar: Snackbar,
  Mui__material__SnackbarContent: SnackbarContent,
  Mui__material__SpeedDial: SpeedDial,
  Mui__material__SpeedDialAction: SpeedDialAction,
  Mui__material__SpeedDialIcon: SpeedDialIcon,
  Mui__material__Stack: Stack,
  Mui__material__Step: Step,
  Mui__material__StepButton: StepButton,
  Mui__material__StepConnector: StepConnector,
  Mui__material__StepContent: StepContent,
  Mui__material__StepIcon: StepIcon,
  Mui__material__StepLabel: StepLabel,
  Mui__material__Stepper: Stepper,
  Mui__material__SvgIcon: SvgIcon,
  Mui__material__SwipeableDrawer: (props) => createElement(SwipeableDrawer, props),
  Mui__material__Switch: Switch,
  Mui__material__Tab: Tab,
  Mui__material__Table: Table,
  Mui__material__TableBody: TableBody,
  Mui__material__TableCell: TableCell,
  Mui__material__TableContainer: TableContainer,
  Mui__material__TableFooter: TableFooter,
  Mui__material__TableHead: TableHead,
  Mui__material__TablePagination: TablePagination,
  Mui__material__TableRow: TableRow,
  Mui__material__TableSortLabel: TableSortLabel,
  Mui__material__Tabs: Tabs,
  Mui__material__TabScrollButton: TabScrollButton,
  Mui__material__TextField: TextField,
  Mui__material__TextareaAutosize: TextareaAutosize,
  Mui__material__ToggleButton: ToggleButton,
  Mui__material__ToggleButtonGroup: ToggleButtonGroup,
  Mui__material__Toolbar: Toolbar,
  Mui__material__Tooltip: Tooltip,
  Mui__material__Typography: Typography,
  Mui__material__Zoom: Zoom,
};

const PyConKRCommonMDXComponents: MDXComponents = {
  Common__Components__Lottie: LottiePlayer,
  Common__Components__NetworkLottie: NetworkLottiePlayer,
  Common__Components__MDX__Confetti: Confetti,
  Common__Components__MDX__PrimaryStyledDetails: PrimaryStyledDetails,
  Common__Components__MDX__SecondaryStyledDetails: SecondaryStyledDetails,
  Common__Components__MDX__Map: MDXMap,
  Common__Components__MDX__FAQAccordion: FAQAccordion,
  Common__Components__MDX__FullWidthStyledButton: StyledFullWidthButton,
  Common__Components__Session__List: SessionList,
  Common__Components__Session__TimeTable: SessionTimeTable,
};

const PythonKRShopMDXComponents: MDXComponents = {
  Shop__Common__PriceDisplay: PriceDisplay,
  Shop__Common__SignInGuard: SignInGuard,
  Shop__Common__ContextProvider: ShopContextProvider,
  Shop__Common__UserSignInMethod: UserSignInMethod,
  Shop__Common__UserSignInAccount: UserSignInAccount,
  Shop__Feature__CartStatus: CartStatus,
  Shop__Feature__ProductList: ProductList,
  Shop__Feature__ProductImageCardList: ProductImageCardList,
  Shop__Feature__OrderList: OrderList,
  Shop__Feature__UserInfo: UserInfo,
  Shop__Feature__PatronList: PatronList,
};

export const PyConKRMDXComponents = {
  ...MUIMDXComponents,
  ...PyConKRCommonMDXComponents,
  ...PythonKRShopMDXComponents,
};
